<a href="https://colab.research.google.com/github/Rituparnaswain/Assignments-Data-Structures-in-Python/blob/main/Assignment_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#1. Create a NumPy array 'arr' of integers from 0 to 5 and print its data type

In [ ]:
import numpy as np

arr = np.array([0, 1, 2, 3, 4, 5])
print(arr.dtype)


int64


In [ ]:
#2. Given a NumPy array 'arr', check if its data type is float64


arr = np.array([1.5, 2.6, 3.7])

In [ ]:
print(arr.dtype)

float64


In [ ]:
#3. Create a NumPy array 'arr' with a data type of complex128 containing three complex numbers.

In [ ]:
import numpy as np
arr = np.array([1 + 2j, 3 + 4j, 5 + 6j], dtype=np.complex128)
print(arr)

[1.+2.j 3.+4.j 5.+6.j]


In [ ]:
#4. Convert an existing NumPy array 'arr' of integers to float32 data type.

In [ ]:
import numpy as np

# Assuming arr is your existing NumPy array of integers
arr = np.array([1, 2, 3, 4, 5])

# Converting to float32 data type
arr_float32 = arr.astype(np.float32)

# Printing the converted array and its data type
print(arr_float32)
print(arr_float32.dtype)


[1. 2. 3. 4. 5.]
float32


In [ ]:
#5. Given a NumPy array 'arr' with float64 data type, convert it to float32 to reduce decimal precision.

In [ ]:
import numpy as np

# Assuming arr is your existing NumPy array with float64 data type
arr = np.array([0.123456789, 1.23456789, 12.3456789])

# Converting to float32 data type
arr_float32 = arr.astype(np.float32)

# Printing the converted array and its data type
print(arr_float32)
print(arr_float32.dtype)

[ 0.12345679  1.2345679  12.345679  ]
float32


In [ ]:
#6. Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and datatype.

In [ ]:
import numpy as np

def array_attributes(arr):

    shape = arr.shape
    size = arr.size
    dtype = arr.dtype
    return shape, size, dtype

arr = np.array([[1, 2, 3], [4, 5, 6]])
shape, size, dtype = array_attributes(arr)
print("Shape:", shape)
print("Size:", size)
print("Data Type:", dtype)

Shape: (2, 3)
Size: 6
Data Type: int64


In [ ]:
# 7. Create a function array_dimension that takes a NumPy array as input and
# returns its dimensionality.

In [ ]:
import numpy as np

def array_dimension(arr):

    return arr.ndim


arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([1, 2, 3, 4, 5])
arr3 = np.array(42)

print("Dimensionality of arr1:", array_dimension(arr1))
print("Dimensionality of arr2:", array_dimension(arr2))
print("Dimensionality of arr3:", array_dimension(arr3))

Dimensionality of arr1: 2
Dimensionality of arr2: 1
Dimensionality of arr3: 0


In [ ]:
#8. Design a function item_size_info that takes a NumPy array as input and returns the item size and the total size in bytes

In [ ]:
import numpy as np

def item_size_info(arr):

    item_size = arr.itemsize
    total_size = arr.size * item_size
    return item_size, total_size

arr = np.array([[1, 2, 3], [4, 5, 6]])
item_size, total_size = item_size_info(arr)
print("Item Size:", item_size, "bytes")
print("Total Size:", total_size, "bytes")

Item Size: 8 bytes
Total Size: 48 bytes


In [ ]:
#9. Create a function array_strides that takes a NumPy array as input and returns the strides of the array.

In [ ]:
import numpy as np

def array_strides(arr):
    """
    Takes a NumPy array as input and returns its strides.

    Parameters:
        arr (numpy.ndarray): Input NumPy array.

    Returns:
        tuple: A tuple containing the strides of the array.
    """
    return arr.strides
arr = np.array([[1, 2, 3], [4, 5, 6]])
strides = array_strides(arr)
print("Strides:", strides)

Strides: (24, 8)


In [ ]:
#10. Design a function shape_stride_relationship that takes a NumPy array as input and returns the shape and strides of the array.

In [ ]:
import numpy as np

def shape_stride_relationship(arr):
    """
    Takes a NumPy array as input and returns its shape and strides.

    Parameters:
        arr (numpy.ndarray): Input NumPy array.

    Returns:
        tuple: A tuple containing the shape and strides of the array.
    """
    return arr.shape, arr.strides
arr = np.array([[1, 2, 3], [4, 5, 6]])
shape, strides = shape_stride_relationship(arr)
print("Shape:", shape)
print("Strides:", strides)

Shape: (2, 3)
Strides: (24, 8)


In [ ]:
# 11. Create a function `create_zeros_array` that takes an integer `n` as input and returns a NumPy array of zeros with `n` elements

In [ ]:
import numpy as np

def create_zeros_array(n):
    """
    Creates a NumPy array of zeros with n elements.

    Parameters:
        n (int): Number of elements in the array.

    Returns:
        numpy.ndarray: NumPy array of zeros with n elements.
    """
    return np.zeros(n)
n = 5
zeros_arr = create_zeros_array(n)
print(zeros_arr)

[0. 0. 0. 0. 0.]


In [ ]:
#12. Write a function `create_ones_matrix` that takes integers `rows` and `cols` as inputs and generates a 2D NumPy array filled with ones of size `rows x cols`.

In [ ]:
import numpy as np

def create_ones_matrix(rows, cols):
   return np.ones((rows, cols))
rows = 3
cols = 4
ones_matrix = create_ones_matrix(rows, cols)
print(ones_matrix)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
#13. Write a function `generate_range_array` that takes three integers start, stop, and step as arguments and creates a NumPy array with a range starting from `start`, ending at stop (exclusive), and with the specified step`.

In [ ]:
import numpy as np

def generate_range_array(start, stop, step):
    """
    Creates a NumPy array with a range starting from start, ending at stop (exclusive),
    and with the specified step.

    Parameters:
        start (int): Starting value of the range.
        stop (int): Ending value of the range (exclusive).
        step (int): Step size between consecutive elements.

    Returns:
        numpy.ndarray: NumPy array containing the generated range.
    """
    return np.arange(start, stop, step)

start = 1
stop = 10
step = 2
range_array = generate_range_array(start, stop, step)
print(range_array)


[1 3 5 7 9]


In [ ]:
#14. Design a function `generate_linear_space` that takes two floats `start`, `stop`, and an integer `num` as
#arguments and generates a NumPy array with num equally spaced values between `start` and `stop`(inclusive).

In [ ]:
import numpy as np

def generate_linear_space(start, stop, num):
    """
    Generate num equally spaced values between start and stop (inclusive).

    Parameters:
    start (float): The start of the linear space.
    stop (float): The end of the linear space.
    num (int): The number of values to generate.

    Returns:
    numpy.ndarray: Array of equally spaced values.
    """
    return np.linspace(start, stop, num)

start = 0
stop = 10
num = 5
result = generate_linear_space(start, stop, num)
print(result)


[ 0.   2.5  5.   7.5 10. ]


In [ ]:
#15. Create a function `create_identity_matrix` that takes an integer `n` as input and generates a square
#identity matrix of size `n x n` using `numpy.eye`.

In [ ]:
import numpy as np

def create_identity_matrix(n):
    """
    Create a square identity matrix of size n x n.

    Parameters:
    n (int): Size of the identity matrix.

    Returns:
    numpy.ndarray: Identity matrix of size n x n.
    """
    return np.eye(n)

n = 3
identity_matrix = create_identity_matrix(n)
print(identity_matrix)



[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#16. Write a function that takes a Python list and converts it into a NumPy array.


In [ ]:
l =[1,2,3,4]
arr = np.array(l)
arr

array([1, 2, 3, 4])

In [ ]:
import numpy as np

def list_to_numpy_array(py_list):
    return np.array(py_list)

python_list = [1, 2, 3, 4, 5]
numpy_array = list_to_numpy_array(python_list)
print(numpy_array)


[1 2 3 4 5]


In [ ]:
#17. Create a NumPy array and demonstrate the use of `numpy.view` to create a new array object with thesame data.

In [ ]:
import numpy as np

# Create a NumPy array
original_array = np.array([1, 2, 3, 4, 5])

# Create a view of the original array
view_array = original_array.view()

# Modify the view array
view_array[0] = 10

# Print both arrays
print("Original array:", original_array)
print("View array:", view_array)


Original array: [10  2  3  4  5]
View array: [10  2  3  4  5]


In [ ]:
#18. Write a function that takes two NumPy arrays and concatenates them along a specified axis.

In [ ]:
import numpy as np

def concatenate_arrays(array1, array2, axis=0):
    """
    Concatenate two NumPy arrays along a specified axis.

    Parameters:
    array1 (numpy.ndarray): First NumPy array to concatenate.
    array2 (numpy.ndarray): Second NumPy array to concatenate.
    axis (int, optional): Axis along which arrays will be concatenated. Default is 0.

    Returns:
    numpy.ndarray: Concatenated array.
    """
    return np.concatenate((array1, array2), axis=axis)

# Example usage:
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6]])
concatenated_array = concatenate_arrays(array1, array2, axis=0)
print("Concatenated array along axis 0:")
print(concatenated_array)

# Concatenating along a different axis
concatenated_array_axis_1 = concatenate_arrays(array1, array2.T, axis=1)
print("\nConcatenated array along axis 1:")
print(concatenated_array_axis_1)


Concatenated array along axis 0:
[[1 2]
 [3 4]
 [5 6]]

Concatenated array along axis 1:
[[1 2 5]
 [3 4 6]]


In [ ]:
#19. Create two NumPy arrays with different shapes and concatenate them horizontally using `numpy.concatenate

In [ ]:
import numpy as np

# Create two NumPy arrays with different shapes
array1 = np.array([[1, 2, 3],
                   [4, 5, 6]])
array2 = np.array([[7, 8],
                   [9, 10]])

# Concatenate them horizontally
concatenated_array = np.concatenate((array1, array2), axis=1)

print("Array 1:")
print(array1)
print("\nArray 2:")
print(array2)
print("\nConcatenated horizontally:")
print(concatenated_array)


Array 1:
[[1 2 3]
 [4 5 6]]

Array 2:
[[ 7  8]
 [ 9 10]]

Concatenated horizontally:
[[ 1  2  3  7  8]
 [ 4  5  6  9 10]]


In [ ]:
#20. Write a function that vertically stacks multiple NumPy arrays given as a list.

In [ ]:
import numpy as np

def stack_arrays_vertically(arrays):
    """
    Vertically stack multiple NumPy arrays given as a list.

    Parameters:
    arrays (list): List of NumPy arrays to vertically stack.

    Returns:
    numpy.ndarray: Vertically stacked array.
    """
    return np.vstack(arrays)

array1 = np.array([[1, 2, 3],
                   [4, 5, 6]])
array2 = np.array([[7, 8, 9],
                   [10, 11, 12]])
array3 = np.array([[13, 14, 15],
                   [16, 17, 18]])

stacked_array = stack_arrays_vertically([array1, array2, array3])
print("Vertically stacked array:")
print(stacked_array)


Vertically stacked array:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]


In [ ]:
#21. Write a Python function using NumPy to create an array of integers within a specified range (inclusive) with a given step size

In [ ]:
import numpy as np

def create_integer_array(start, stop, step):
    """
    Create an array of integers within a specified range (inclusive) with a given step size.

    Parameters:
    start (int): Start of the range (inclusive).
    stop (int): End of the range (inclusive).
    step (int): Step size between integers.

    Returns:
    numpy.ndarray: Array of integers within the specified range with the given step size.
    """
    return np.arange(start, stop + 1, step, dtype=int)

start = 1
stop = 10
step = 2
result = create_integer_array(start, stop, step)
print(result)


[1 3 5 7 9]


In [ ]:
#22. Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1 (inclusive).

In [ ]:
import numpy as np

def generate_equally_spaced_values():
    """
    Generate an array of 10 equally spaced values between 0 and 1 (inclusive).

    Returns:
    numpy.ndarray: Array of 10 equally spaced values between 0 and 1.
    """
    return np.linspace(0, 1, 10)

result = generate_equally_spaced_values()
print(result)


[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [ ]:
#23. Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and 1000 (inclusive).


In [ ]:
import numpy as np

def generate_logarithmically_spaced_values():
    """
    Generate an array of 5 logarithmically spaced values between 1 and 1000 (inclusive).

    Returns:
    numpy.ndarray: Array of 5 logarithmically spaced values between 1 and 1000.
    """
    return np.logspace(start=0, stop=3, num=5)

# Example usage:
result = generate_logarithmically_spaced_values()
print(result)


[   1.            5.62341325   31.6227766   177.827941   1000.        ]


In [ ]:
# 24. Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns, where the values are random integers between 1 and 100.

In [ ]:
import numpy as np
import pandas as pd

# Generate a NumPy array with random integers
random_array = np.random.randint(1, 101, size=(5, 3))

# Create a Pandas DataFrame from the NumPy array
df = pd.DataFrame(random_array, columns=['Column1', 'Column2', 'Column3'])

# Display the DataFrame
print(df)


   Column1  Column2  Column3
0       50       29       35
1       58       14       27
2       98        8       92
3       22       37       98
4       17       74       18


In [ ]:
#25. Write a function that takes a Pandas DataFrame and replaces all negative values in a specific column with zeros. Use NumPy operations within the Pandas DataFrame.

In [ ]:
import pandas as pd

def replace_negatives_with_zeros(dataframe, column_name):
    """
    Replace all negative values in a specific column of a Pandas DataFrame with zeros.

    Parameters:
    dataframe (pandas.DataFrame): The input Pandas DataFrame.
    column_name (str): The name of the column containing the values to be replaced.

    Returns:
    pandas.DataFrame: DataFrame with negative values replaced by zeros in the specified column.
    """
    # Replace negative values with zeros using NumPy's where function
    dataframe[column_name] = np.where(dataframe[column_name] < 0, 0, dataframe[column_name])
    return dataframe

data = {'A': [1, -2, 3, -4, 5],
        'B': [-1, 2, -3, 4, 5],
        'C': [1, 2, 3, 4, 5]}
df = pd.DataFrame(data)

print("Original DataFrame:")
print(df)

column_name = 'B'
df_modified = replace_negatives_with_zeros(df, column_name)

print("\nDataFrame with negative values replaced by zeros in column '{}':".format(column_name))
print(df_modified)


Original DataFrame:
   A  B  C
0  1 -1  1
1 -2  2  2
2  3 -3  3
3 -4  4  4
4  5  5  5

DataFrame with negative values replaced by zeros in column 'B':
   A  B  C
0  1  0  1
1 -2  2  2
2  3  0  3
3 -4  4  4
4  5  5  5


In [ ]:
#26. Access the 3rd element from the given NumPy array.
 # arr = np.array([10, 20, 30, 40, 50])

In [ ]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])
third_element = arr[2]
print(third_element)



30


In [ ]:
# 27. Retrieve the element at index (1, 2) from the 2D NumPy array.

In [ ]:
arr_2d = np.array([[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])

In [ ]:
import numpy as np

# Define the 2D NumPy array
arr_2d = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

# Retrieve the element at index (1, 2)
element = arr_2d[1, 2]
print(element)


6


In [ ]:
# 28. Using boolean indexing, extract elements greater than 5 from the given NumPy array.
arr = np.array([3, 8, 2, 10, 5, 7])

In [ ]:
import numpy as np

# Define the NumPy array
arr = np.array([3, 8, 2, 10, 5, 7])

# Boolean indexing to extract elements greater than 5
result = arr[arr > 5]
print(result)



[ 8 10  7]


In [ ]:
# 29. Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array.
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
import numpy as np

# Define the NumPy array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Perform basic slicing to extract elements from index 2 to 5 (inclusive)
result = arr[2:6]
print(result)


[3 4 5 6]


In [ ]:
#30. Slice the 2D NumPy array to extract the sub-array `[[2, 3], [5, 6]]` from the given array.
arr_2d = np.array([[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])


In [ ]:
import numpy as np

# Define the 2D NumPy array
arr_2d = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

# Slice the array to extract the sub-array [[2, 3], [5, 6]]
sub_array = arr_2d[0:2, 1:3]
print(sub_array)


[[2 3]
 [5 6]]


In [ ]:
#31.Write a NumPy function to extract elements in specific order from a given 2D array based on indices
#provided in another array.

In [ ]:
import numpy as np

def extract_elements(arr_2d, indices):
    """
    Extract elements from a given 2D array based on indices provided in another array.

    Parameters:
        arr_2d (numpy.ndarray): The 2D array from which elements will be extracted.
        indices (numpy.ndarray): The array containing indices to extract elements.

    Returns:
        numpy.ndarray: The extracted elements based on the provided indices.
    """
    # Flatten the 2D array
    flattened_arr = arr_2d.flatten()

    # Extract elements based on indices
    extracted_elements = flattened_arr[indices]

    return extracted_elements

arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

indices = np.array([1, 3, 4, 7, 8])

result = extract_elements(arr_2d, indices)
print(result)


[2 4 5 8 9]


In [ ]:
#32. Create a NumPy function that filters elements greater than a threshold from a given 1D array using
#boolean indexing.

In [ ]:
import numpy as np

def filter_elements(arr, threshold):
    """
    Filter elements greater than a threshold from a given 1D array using boolean indexing.

    Parameters:
        arr (numpy.ndarray): The 1D array to be filtered.
        threshold (int or float): The threshold value for filtering.

    Returns:
        numpy.ndarray: The filtered array containing elements greater than the threshold.
    """
    # Use boolean indexing to filter elements greater than the threshold
    filtered_arr = arr[arr > threshold]

    return filtered_arr


arr = np.array([1, 5, 10, 15, 20])
threshold = 10

result = filter_elements(arr, threshold)
print(result)


[15 20]


In [ ]:
# 33. Develop a NumPy function that extracts specific elements from a 3D array using indices provided in three
# separate arrays for each dimension.

In [ ]:
import numpy as np

def extract_elements_3d(arr_3d, indices_dim1, indices_dim2, indices_dim3):
    """
    Extract specific elements from a 3D array using indices provided in three separate arrays for each dimension.

    Parameters:
        arr_3d (numpy.ndarray): The 3D array from which elements will be extracted.
        indices_dim1 (numpy.ndarray): The array containing indices for the first dimension.
        indices_dim2 (numpy.ndarray): The array containing indices for the second dimension.
        indices_dim3 (numpy.ndarray): The array containing indices for the third dimension.

    Returns:
        numpy.ndarray: The extracted elements based on the provided indices.
    """
    # Ensure indices arrays have the same length
    assert len(indices_dim1) == len(indices_dim2) == len(indices_dim3), "Indices arrays must have the same length"

    # Extract elements based on indices
    extracted_elements = arr_3d[indices_dim1, indices_dim2, indices_dim3]

    return extracted_elements


arr_3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
indices_dim1 = np.array([0, 1])
indices_dim2 = np.array([0, 1])
indices_dim3 = np.array([1, 2])

result = extract_elements_3d(arr_3d, indices_dim1, indices_dim2, indices_dim3)
print(result)


[ 2 12]


In [ ]:

#35. Create a NumPy function that extracts elements from a 2D array using row and column indices provided
# in separate arrays.

In [ ]:
import numpy as np

def extract_elements_2d(arr_2d, row_indices, col_indices):
    """
    Extract elements from a 2D array using row and column indices provided in separate arrays.

    Parameters:
        arr_2d (numpy.ndarray): The 2D array from which elements will be extracted.
        row_indices (numpy.ndarray): The array containing row indices.
        col_indices (numpy.ndarray): The array containing column indices.

    Returns:
        numpy.ndarray: The extracted elements based on the provided row and column indices.
    """
    # Ensure row and column indices arrays have the same length
    assert len(row_indices) == len(col_indices), "Row and column indices arrays must have the same length"

    # Extract elements based on row and column indices
    extracted_elements = arr_2d[row_indices, col_indices]

    return extracted_elements

arr_2d = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])
row_indices = np.array([0, 1, 2])
col_indices = np.array([1, 2, 0])

result = extract_elements_2d(arr_2d, row_indices, col_indices)
print(result)


[2 6 7]


In [ ]:
# 36. Given an array arr of shape (3, 3), add a scalar value of 5 to each
# element using NumPy broadcasting.

In [ ]:
import numpy as np

# Create the array
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Add a scalar value of 5 to each element using broadcasting
result = arr + 5

print(result)


[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [ ]:
# 37. Consider two arrays arr1 of shape (1, 3) and arr2 of shape (3, 4). Multiply each row of arr2 by the
#corresponding element in arr1 using NumPy broadcasting

In [ ]:
import numpy as np

# Define arrays arr1 and arr2
arr1 = np.array([[2, 3, 4]])
arr2 = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9, 10, 11, 12]])

# Reshape arr1 to match the shape of arr2
arr1_reshaped = arr1.reshape(3, 1)

# Multiply each row of arr2 by the corresponding element in arr1 using broadcasting
result = arr1_reshaped * arr2

print(result)


[[ 2  4  6  8]
 [15 18 21 24]
 [36 40 44 48]]


In [ ]:
#38. Given a 1D array arr1 of shape (1, 4) and a 2D array arr2 of shape (4, 3), add arr1 to each row of arr2 using
# NumPy broadcasting.

In [ ]:
import numpy as np

# Define arrays arr1 and arr2
arr1 = np.array([[1, 2, 3, 4]])
arr2 = np.array([[5, 6, 7],
                 [8, 9, 10],
                 [11, 12, 13],
                 [14, 15, 16]])

# Transpose arr1 to shape (4, 1) to make it compatible for broadcasting
arr1_transposed = arr1.T

# Add arr1 to each row of arr2 using broadcasting
result = arr2 + arr1_transposed

print(result)


[[ 6  7  8]
 [10 11 12]
 [14 15 16]
 [18 19 20]]


In [ ]:
#39. Consider two arrays arr1 of shape (3, 1) and arr2 of shape (1, 3). Add these arrays using NumPy
#broadcasting.

In [ ]:
import numpy as np

# Define arrays arr1 and arr2
arr1 = np.array([[1],
                 [2],
                 [3]])
arr2 = np.array([[4, 5, 6]])

# Add arr1 and arr2 using broadcasting
result = arr1 + arr2

print(result)


[[5 6 7]
 [6 7 8]
 [7 8 9]]


In [ ]:
#40. Given arrays arr1 of shape (2, 3) and arr2 of shape (2, 2), perform multiplication using NumPy
#broadcasting. Handle the shape incompatibility

In [ ]:
import numpy as np

# Define arrays arr1 and arr2
arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])
arr2 = np.array([[1, 2],
                 [3, 4]])

# Reshape arr2 to shape (2, 2, 1) to make it compatible for broadcasting
arr2_reshaped = arr2.reshape(2, 2, 1)

# Perform multiplication using broadcasting
result = arr1 * arr2_reshaped

print(result)



[[[ 1  2  3]
  [ 8 10 12]]

 [[ 3  6  9]
  [16 20 24]]]


In [ ]:
#41. Calculate column-wise mean for the given array
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [ ]:
import numpy as np

# Define the array
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

# Calculate column-wise mean
column_means = np.mean(arr, axis=0)

print(column_means)


[2.5 3.5 4.5]


In [ ]:
#42. Find maximum value in each row of the given array
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [ ]:
import numpy as np

# Define the array
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

# Find maximum value in each row
max_values_per_row = np.amax(arr, axis=1)

print(max_values_per_row)


[3 6]


In [ ]:
#43. For the given array, find indices of maximum value in each column
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [ ]:
import numpy as np

# Define the array
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

# Find indices of maximum value in each column
max_indices_per_column = np.argmax(arr, axis=0)

print(max_indices_per_column)


[1 1 1]


In [ ]:
#44. For the given array, apply custom function to calculate moving sum along rows.
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [ ]:
import numpy as np

# Define the custom function to calculate moving sum along rows
def moving_sum(arr, window_size):
    # Define an empty list to store the moving sum results
    moving_sum_result = []

    # Iterate over each row in the array
    for row in arr:
        # Initialize an empty list to store the moving sum for the current row
        row_moving_sum = []
        # Iterate over each element in the row
        for i in range(len(row) - window_size + 1):
            # Calculate the moving sum for the current window
            window_sum = sum(row[i:i+window_size])
            # Append the moving sum to the list
            row_moving_sum.append(window_sum)
        # Append the moving sum for the current row to the final result
        moving_sum_result.append(row_moving_sum)

    # Convert the result to a NumPy array
    return np.array(moving_sum_result)

# Define the array
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

# Define the window size for moving sum
window_size = 2

# Calculate the moving sum along rows using the custom function
moving_sum_result = moving_sum(arr, window_size)

print(moving_sum_result)


[[ 3  5]
 [ 9 11]]


In [ ]:
#45. In the given array, check if all elements in each column are even.
arr = np.array([[2, 4, 6], [3, 5, 7]])

In [ ]:
import numpy as np

# Define the array
arr = np.array([[2, 4, 6],
                [3, 5, 7]])

# Check if all elements in each column are even
are_all_even = np.all(arr % 2 == 0, axis=0)

print(are_all_even)


[False False False]


In [ ]:
#46. Given a NumPy array arr, reshape it into a matrix of dimensions `m` rows and `n` columns. Return the
#reshaped matrix.
original_array = np.array([1, 2, 3, 4, 5, 6])

In [ ]:
import numpy as np

# Define the original array
original_array = np.array([1, 2, 3, 4, 5, 6])

# Define the dimensions of the desired matrix
m = 2  # Number of rows
n = 3  # Number of columns

# Reshape the original array into a matrix of dimensions m rows and n columns
reshaped_matrix = original_array.reshape(m, n)

print(reshaped_matrix)


[[1 2 3]
 [4 5 6]]


In [ ]:
#47. Create a function that takes a matrix as input and returns the flattened array.
input_matrix = np.array([[1, 2, 3], [4, 5, 6]])

In [ ]:
import numpy as np

def flatten_matrix(input_matrix):
    """
    Flatten the input matrix into a 1D array.

    Parameters:
        input_matrix (numpy.ndarray): The input matrix to be flattened.

    Returns:
        numpy.ndarray: The flattened array.
    """
    # Flatten the input matrix
    flattened_array = input_matrix.flatten()

    return flattened_array

# Define the input matrix
input_matrix = np.array([[1, 2, 3],
                         [4, 5, 6]])

# Flatten the input matrix
flattened_array = flatten_matrix(input_matrix)

print(flattened_array)


[1 2 3 4 5 6]


In [ ]:
#48. Write a function that concatenates two given arrays along a specified axis.
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

In [ ]:
import numpy as np

def concatenate_arrays(array1, array2, axis=0):
    """
    Concatenate two given arrays along a specified axis.

    Parameters:
        array1 (numpy.ndarray): The first array to be concatenated.
        array2 (numpy.ndarray): The second array to be concatenated.
        axis (int, optional): The axis along which the arrays will be concatenated. Default is 0.

    Returns:
        numpy.ndarray: The concatenated array.
    """
    # Concatenate the arrays along the specified axis
    concatenated_array = np.concatenate((array1, array2), axis=axis)

    return concatenated_array

# Define the arrays
array1 = np.array([[1, 2],
                   [3, 4]])
array2 = np.array([[5, 6],
                   [7, 8]])

# Concatenate the arrays along axis 0 (rows)
concatenated_array_rows = concatenate_arrays(array1, array2, axis=0)
print("Concatenated along rows:\n", concatenated_array_rows)

# Concatenate the arrays along axis 1 (columns)
concatenated_array_columns = concatenate_arrays(array1, array2, axis=1)
print("\nConcatenated along columns:\n", concatenated_array_columns)


Concatenated along rows:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

Concatenated along columns:
 [[1 2 5 6]
 [3 4 7 8]]


In [ ]:
#49. Create a function that splits an array into multiple sub-arrays along a specified axis.
original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [ ]:
import numpy as np

def split_array(original_array, num_splits, axis=0):
    """
    Split an array into multiple sub-arrays along a specified axis.

    Parameters:
        original_array (numpy.ndarray): The original array to be split.
        num_splits (int): The number of splits.
        axis (int, optional): The axis along which to split the array. Default is 0.

    Returns:
        list of numpy.ndarray: The list of sub-arrays.
    """
    # Split the original array along the specified axis
    sub_arrays = np.split(original_array, num_splits, axis=axis)

    return sub_arrays

# Define the original array
original_array = np.array([[1, 2, 3],
                           [4, 5, 6],
                           [7, 8, 9]])

# Split the original array into 3 sub-arrays along axis 0 (rows)
sub_arrays = split_array(original_array, num_splits=3, axis=0)
print("Sub-arrays along rows:")
for arr in sub_arrays:
    print(arr)

# Split the original array into 3 sub-arrays along axis 1 (columns)
sub_arrays = split_array(original_array, num_splits=3, axis=1)
print("\nSub-arrays along columns:")
for arr in sub_arrays:
    print(arr)


Sub-arrays along rows:
[[1 2 3]]
[[4 5 6]]
[[7 8 9]]

Sub-arrays along columns:
[[1]
 [4]
 [7]]
[[2]
 [5]
 [8]]
[[3]
 [6]
 [9]]


In [ ]:
#50. Write a function that inserts and then deletes elements from a given array at specified indices.
original_array = np.array([1, 2, 3, 4, 5])
indices_to_insert = [2, 4]
values_to_insert = [10, 11]
indices_to_delete = [1, 3]

In [ ]:
import numpy as np

def insert_and_delete_elements(original_array, indices_to_insert, values_to_insert, indices_to_delete):
    """
    Inserts elements into and deletes elements from a given array at specified indices.

    Parameters:
        original_array (numpy.ndarray): The original array.
        indices_to_insert (list): The indices where elements will be inserted.
        values_to_insert (list): The values to be inserted at the specified indices.
        indices_to_delete (list): The indices of elements to be deleted.

    Returns:
        numpy.ndarray: The modified array after insertion and deletion.
    """
    # Insert elements into the original array at specified indices
    modified_array = np.insert(original_array, indices_to_insert, values_to_insert)

    # Delete elements from the modified array at specified indices
    modified_array = np.delete(modified_array, indices_to_delete)

    return modified_array

# Define the original array
original_array = np.array([1, 2, 3, 4, 5])

# Define indices to insert elements
indices_to_insert = [2, 4]

# Define values to insert at specified indices
values_to_insert = [10, 11]

# Define indices to delete elements
indices_to_delete = [1, 3]

# Insert and delete elements from the original array
modified_array = insert_and_delete_elements(original_array, indices_to_insert, values_to_insert, indices_to_delete)
print("Modified array:", modified_array)


Modified array: [ 1 10  4 11  5]


In [ ]:
# 51. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 10.
# Perform element-wise addition between `arr1` and `arr2`

In [ ]:
# Proper definition and usage of variables
import numpy as np

# Define arr1 and arr2 correctly
arr1 = np.random.randint(0, 100, size=10)
arr2 = np.arange(1, 11)

# Perform the element-wise addition
result = arr1 + arr2

# Print the arrays and the result
print("arr1:", arr1)
print("arr2:", arr2)
print("result:", result)





arr1: [13 40 13 39 32 65 16 80 92 10]
arr2: [ 1  2  3  4  5  6  7  8  9 10]
result: [ 14  42  16  43  37  71  23  88 101  20]


In [ ]:
# 52. Generate a NumPy array `arr1` with sequential integers from 10 to 1 and another array `arr2` with integers
# from 1 to 10. Subtract `arr2` from `arr1` element-wise.

In [ ]:
import numpy as np

# Generate arr1 with sequential integers from 10 to 1
arr1 = np.arange(10, 0, -1)

# Generate arr2 with integers from 1 to 10
arr2 = np.arange(1, 11)

# Subtract arr2 from arr1 element-wise
result = arr1 - arr2

print("arr1:", arr1)
print("arr2:", arr2)
print("Result of arr1 - arr2:", result)


arr1: [10  9  8  7  6  5  4  3  2  1]
arr2: [ 1  2  3  4  5  6  7  8  9 10]
Result of arr1 - arr2: [ 9  7  5  3  1 -1 -3 -5 -7 -9]


In [ ]:
#53. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 5.
#Perform element-wise multiplication between `arr1` and `arr2`

In [ ]:
import numpy as np

# Create arr1 with random integers
arr1 = np.random.randint(1, 10, size=(5, 5))  # Adjust the size as needed
print("arr1:")
print(arr1)

# Create arr2 with integers from 1 to 5
arr2 = np.arange(1, 6)
print("\narr2:")
print(arr2)

# Perform element-wise multiplication
result = arr1 * arr2
print("\nElement-wise multiplication:")
print(result)


arr1:
[[5 3 5 8 9]
 [1 3 6 8 5]
 [7 1 9 2 1]
 [6 4 8 8 8]
 [8 2 5 3 9]]

arr2:
[1 2 3 4 5]

Element-wise multiplication:
[[ 5  6 15 32 45]
 [ 1  6 18 32 25]
 [ 7  2 27  8  5]
 [ 6  8 24 32 40]
 [ 8  4 15 12 45]]


In [ ]:
# 54. Generate a NumPy array `arr1` with even integers from 2 to 10 and another array `arr2` with integers from 1
#to 5. Perform element-wise division of `arr1` by `arr2`.

In [ ]:
import numpy as np

# Generate arr1 with even integers from 2 to 10
arr1 = np.arange(2, 11, 2)
print("arr1:")
print(arr1)

# Generate arr2 with integers from 1 to 5
arr2 = np.arange(1, 6)
print("\narr2:")
print(arr2)

# Perform element-wise division
result = arr1 / arr2
print("\nElement-wise division:")
print(result)


arr1:
[ 2  4  6  8 10]

arr2:
[1 2 3 4 5]

Element-wise division:
[2. 2. 2. 2. 2.]


In [ ]:
# 55. Create a NumPy array `arr1` with integers from 1 to 5 and another array `arr2` with the same numbers
#reversed. Calculate the exponentiation of `arr1` raised to the power of `arr2` element-wise.

In [ ]:
import numpy as np

# Create arr1 with integers from 1 to 5
arr1 = np.arange(1, 6)
print("arr1:")
print(arr1)

# Create arr2 with the same numbers reversed
arr2 = np.flip(arr1)
print("\narr2:")
print(arr2)

# Calculate the exponentiation of arr1 raised to the power of arr2 element-wise
result = np.power(arr1, arr2)
print("\nExponentiation of arr1 raised to the power of arr2 element-wise:")
print(result)


arr1:
[1 2 3 4 5]

arr2:
[5 4 3 2 1]

Exponentiation of arr1 raised to the power of arr2 element-wise:
[ 1 16 27 16  5]


In [ ]:
#56. Write a function that counts the occurrences of a specific substring within a NumPy array of string
 #arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])

In [ ]:
import numpy as np

def count_substring_occurrences(arr, substr):
    # Vectorized approach using np.char.count
    counts = np.char.count(arr, substr)
    total_occurrences = np.sum(counts)
    return total_occurrences

# Example usage:
arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])
substring = 'hello'
occurrences = count_substring_occurrences(arr, substring)
print(f"The substring '{substring}' occurs {occurrences} times in the array.")


The substring 'hello' occurs 3 times in the array.


In [ ]:
# 57. Write a function that extracts uppercase characters from a NumPy array of strings.

#arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])

In [ ]:
import numpy as np

def extract_uppercase(arr):
    # Initialize an empty list to store the uppercase characters
    uppercase_chars = []

    # Iterate over each string in the array
    for string in arr:
        # Use list comprehension to extract uppercase characters from each string
        uppercase_chars.extend([char for char in string if char.isupper()])

    # Convert the list of uppercase characters to a NumPy array
    uppercase_arr = np.array(uppercase_chars)

    return uppercase_arr

# Example usage:
arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])
uppercase_chars = extract_uppercase(arr)
print("Uppercase characters extracted from the array:", uppercase_chars)


Uppercase characters extracted from the array: ['H' 'W' 'O' 'A' 'I' 'G' 'P' 'T']


In [ ]:
#58. Write a function that replaces occurrences of a substring in a NumPy array of strings with a new string.

#arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

In [ ]:
import numpy as np

def replace_substring(arr, old_substring, new_substring):
    # Vectorized approach using np.char.replace
    replaced_arr = np.char.replace(arr, old_substring, new_substring)
    return replaced_arr

# Example usage:
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
old_substring = 'apple'
new_substring = 'orange'
new_arr = replace_substring(arr, old_substring, new_substring)
print("Original array:", arr)
print("Array after replacement:", new_arr)


Original array: ['apple' 'banana' 'grape' 'pineapple']
Array after replacement: ['orange' 'banana' 'grape' 'pineorange']


In [ ]:
# 59. Write a function that concatenates strings in a NumPy array element-wise


In [ ]:
import numpy as np

def concatenate_strings_elementwise(arr1, arr2):
    # Ensure the input arrays are NumPy arrays
    arr1 = np.array(arr1, dtype=str)
    arr2 = np.array(arr2, dtype=str)

    # Perform element-wise string concatenation
    concatenated = np.char.add(arr1, arr2)

    return concatenated

# Example usage
arr1 = np.array(["hello", "world"])
arr2 = np.array(["_numpy", "_array"])
result = concatenate_strings_elementwise(arr1, arr2)
print(result)



['hello_numpy' 'world_array']


In [ ]:
# 60. Write a function that finds the length of the longest string in a NumPy array.

# arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

In [ ]:
import numpy as np

def find_longest_string_length(arr):
    # Convert each string to its length
    lengths = np.vectorize(len)(arr)
    # Find the maximum length
    max_length = np.max(lengths)
    return max_length

# Example usage
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
print(find_longest_string_length(arr))  # Output should be 9


9


In [ ]:
 # 61. Create a dataset of 100 random integers between 1 and 1000. Compute the mean, median, variance, and
# standard deviation of the dataset using NumPy's functions.


In [ ]:
import numpy as np

# Create a dataset of 100 random integers between 1 and 1000
dataset = np.random.randint(1, 1001, size=100)

# Compute the mean
mean = np.mean(dataset)

# Compute the median
median = np.median(dataset)

# Compute the variance
variance = np.var(dataset)

# Compute the standard deviation
std_deviation = np.std(dataset)

# Print the results
print("Dataset:", dataset)
print("Mean:", mean)
print("Median:", median)
print("Variance:", variance)
print("Standard Deviation:", std_deviation)


Dataset: [173 149 827 252 876 116 674 251 641 948   8 833 938  52 665 274  50  34
 666 660 686 565 121 343 812 387 146 994 553 660 643 869  57 566 305 793
 778 173 438 219 491 993 300 727  59 481 315 444 871 581 441 845 189 870
 440 210 156 212 671 878 525 773 731 656 457 803 655 802 549 910 429 670
 497 771 250 266 678  66 918 404 649 470 956 460 254 331 610 378 308 917
 203 450 650 366 624 612 480  78 477 918]
Mean: 513.7
Median: 511.0
Variance: 75026.29000000001
Standard Deviation: 273.9092733004854


In [ ]:
# 62. Generate an array of 50 random numbers between 1 and 100. Find the 25th and 75th percentiles of the
# dataset.

In [ ]:
import numpy as np

# Generate an array of 50 random numbers between 1 and 100
random_numbers = np.random.randint(1, 101, size=50)

# Compute the 25th percentile
percentile_25 = np.percentile(random_numbers, 25)

# Compute the 75th percentile
percentile_75 = np.percentile(random_numbers, 75)

# Print the results
print("Random Numbers:", random_numbers)
print("25th Percentile:", percentile_25)
print("75th Percentile:", percentile_75)


Random Numbers: [ 38  35  18  89  84  58   4   9  77  45  81  29  38  38  93  36  79  49
  21  33  81  38  95  95  98   2  25  92 100  89  87  57   3  13  60  14
  72  22  10  47  60  49   3  66   4  36  27  50  34  97]
25th Percentile: 25.5
75th Percentile: 80.5


In [ ]:

#63. Create two arrays representing two sets of variables. Compute the correlation coefficient between these
# arrays using NumPy's `corrcoef` function

In [ ]:
import numpy as np

# Step 1: Import NumPy
# (already done above)

# Step 2: Create arr1 with sequential integers from 10 to 1
arr1 = np.arange(10, 0, -1)

# Step 3: Create arr2 with integers from 1 to 10
arr2 = np.arange(1, 11)

# Step 4: Perform element-wise subtraction
result = arr1 - arr2

# Print the arrays and the result
print("arr1:", arr1)
print("arr2:", arr2)
print("result:", result)


arr1: [10  9  8  7  6  5  4  3  2  1]
arr2: [ 1  2  3  4  5  6  7  8  9 10]
result: [ 9  7  5  3  1 -1 -3 -5 -7 -9]


In [ ]:
# 64. Create two matrices and perform matrix multiplication using NumPy's `dot` function.


In [ ]:
import numpy as np
arr1 = np.random.randint(1,2,(3,3))
arr2 = np.random.randint(1,2,(3,3))

arr = np.dot(arr1,arr2)

In [ ]:
arr

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

In [ ]:
arr1@ arr2

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

In [ ]:
# 65. Create an array of 50 integers between 10 and 1000. Calculate the 10th, 50th (median), and 90th
# percentiles along with the first and third quartiles

In [ ]:
import numpy as np

# Create an array of 50 random integers between 10 and 1000
array = np.random.randint(10, 1001, 50)

# Calculate the 10th, 50th (median), and 90th percentiles
percentile_10 = np.percentile(array, 10)
percentile_50 = np.median(array)
percentile_90 = np.percentile(array, 90)

# Calculate the first (25th percentile) and third (75th percentile) quartiles
first_quartile = np.percentile(array, 25)
third_quartile = np.percentile(array, 75)

# Print the results
print("Array of 50 integers between 10 and 1000:")
print(array)

print("\n10th percentile:", percentile_10)
print("50th percentile (Median):", percentile_50)
print("90th percentile:", percentile_90)
print("First quartile (25th percentile):", first_quartile)
print("Third quartile (75th percentile):", third_quartile)


Array of 50 integers between 10 and 1000:
[542 648 123 669 389 552 288 550 192 760 964 434 960 608  93 913 408 416
 401 753 376 266 913 801 579 278 875 353 292 222 317 266 510 321  16 569
 734 363 939 832 417 196  37 812 933 810 984 116 425 265]

10th percentile: 185.10000000000002
50th percentile (Median): 429.5
90th percentile: 915.0
First quartile (25th percentile): 289.0
Third quartile (75th percentile): 758.25


In [ ]:
#66. Create a NumPy array of integers and find the index of a specific element.

In [2]:
import numpy as np
array = np.array([10, 20, 30, 40, 50])
element_to_find = 30
indices = np.where(array == element_to_find)

print("Index of element", element_to_find, "is:", indices[0][0])


Index of element 30 is: 2


In [3]:
# 67. Generate a random NumPy array and sort it in ascending order

In [4]:
import numpy as np

random_array = np.random.rand(10)

print("Random array:", random_array)

sorted_array = np.sort(random_array)

print("Sorted array:", sorted_array)


Random array: [0.8593047  0.07613587 0.12774108 0.22048426 0.54497822 0.06483213
 0.07321143 0.00125436 0.12034319 0.71650041]
Sorted array: [0.00125436 0.06483213 0.07321143 0.07613587 0.12034319 0.12774108
 0.22048426 0.54497822 0.71650041 0.8593047 ]


In [5]:
# 68. Filter elements >20 in the given NumPy array.
arr = np.array([12, 25, 6, 42, 8, 30])

In [6]:
import numpy as np

arr = np.array([12, 25, 6, 42, 8, 30])

filtered_arr = arr[arr > 20]


print("Filtered array (elements > 20):", filtered_arr)


Filtered array (elements > 20): [25 42 30]


In [9]:
# 69. Filter elements which are divisible by 3 from a given NumPy array.
arr = np.array([1, 5, 8, 12, 15])

In [11]:
import numpy as np

arr = np.array([1, 5, 8, 12, 15])

filtered_arr = arr[arr % 3 == 0]


print("Filtered array (elements divisible by 3):", filtered_arr)



Filtered array (elements divisible by 3): [12 15]


In [12]:
# 70. Filter elements which are ≥ 20 and ≤ 40 from a given NumPy array.
arr = np.array([10, 20, 30, 40, 50])

In [13]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

filtered_arr = arr[(arr >= 20) & (arr <= 40)]

print("Filtered array (elements ≥ 20 and ≤ 40):", filtered_arr)


Filtered array (elements ≥ 20 and ≤ 40): [20 30 40]


In [14]:
# 71. For the given NumPy array, check its byte order using the `dtype` attribute byteorder
arr = np.array([1, 2, 3])

In [15]:
import numpy as np

arr = np.array([1, 2, 3])

byte_order = arr.dtype.byteorder

print("Byte order of the array:", byte_order)


Byte order of the array: =


In [16]:
# 72. For the given NumPy array, perform byte swapping in place using `byteswap()`.
arr = np.array([1, 2, 3], dtype=np.int32)

In [17]:
import numpy as np

arr = np.array([1, 2, 3], dtype=np.int32)

arr.byteswap(True)

print("Array after byte swapping:", arr)


Array after byte swapping: [16777216 33554432 50331648]


In [19]:
# 73. For the given NumPy array, swap its byte order without modifying the original array using
#`newbyteorder()`.
arr = np.array([1, 2, 3], dtype=np.int32)

In [20]:
import numpy as np

arr = np.array([1, 2, 3], dtype=np.int32)

swapped_arr = arr.newbyteorder()

print("Original array:", arr)
print("Swapped array:", swapped_arr)


Original array: [1 2 3]
Swapped array: [16777216 33554432 50331648]


In [21]:
# 74. For the given NumPy array and swap its byte order conditionally based on system endianness using
# `newbyteorder()`.
arr = np.array([1, 2, 3], dtype=np.int32)

In [22]:
import numpy as np

arr = np.array([1, 2, 3], dtype=np.int32)

swapped_arr = arr.newbyteorder()

print("Original array:", arr)
print("Swapped array (conditionally based on system endianness):", swapped_arr)


Original array: [1 2 3]
Swapped array (conditionally based on system endianness): [16777216 33554432 50331648]


In [23]:
# 75. For the given NumPy array, check if byte swapping is necessary for the current system using `dtype`
# attribute `byteorder`.
arr = np.array([1, 2, 3], dtype=np.int32)

In [24]:
import numpy as np

arr = np.array([1, 2, 3], dtype=np.int32)

system_byteorder = arr.dtype.byteorder
native_byteorder = np.dtype(np.int32).byteorder
byte_swapping_needed = system_byteorder != native_byteorder

print("Byte order of the system:", system_byteorder)
print("Native byte order of the data type:", native_byteorder)

if byte_swapping_needed:
    print("Byte swapping is necessary for the current system.")
else:
    print("Byte swapping is not necessary for the current system.")


Byte order of the system: =
Native byte order of the data type: =
Byte swapping is not necessary for the current system.


In [25]:
# 76. Create a NumPy array `arr1` with values from 1 to 10. Create a copy of
# `arr1` named `copy_arr` and modify
#an element in `copy_arr`. Check if modifying `copy_arr` affects `arr1`.

In [26]:
import numpy as np

arr1 = np.arange(1, 11)


copy_arr = arr1.copy()


copy_arr[0] = 100


print("Original array arr1:", arr1)
print("Modified copy_arr:", copy_arr)


Original array arr1: [ 1  2  3  4  5  6  7  8  9 10]
Modified copy_arr: [100   2   3   4   5   6   7   8   9  10]


In [27]:
# 77. Create a 2D NumPy array `matrix` of shape (3, 3) with random integers. Extract a slice `view_slice` from
# the matrix. Modify an element in `view_slice` and observe if it changes the original `matrix

In [28]:
import numpy as np

matrix = np.random.randint(1, 100, size=(3, 3))

view_slice = matrix[1:, 1:]

print("Original matrix:")
print(matrix)
print("\nSlice view_slice:")
print(view_slice)

view_slice[0, 0] = 999

print("\nAfter modifying view_slice:")
print("Original matrix:")
print(matrix)
print("\nSlice view_slice:")
print(view_slice)


Original matrix:
[[12 24 34]
 [98  9 50]
 [54 25 41]]

Slice view_slice:
[[ 9 50]
 [25 41]]

After modifying view_slice:
Original matrix:
[[ 12  24  34]
 [ 98 999  50]
 [ 54  25  41]]

Slice view_slice:
[[999  50]
 [ 25  41]]


In [29]:
# 78. Create a NumPy array `array_a` of shape (4, 3) with sequential integers from 1 to 12. Extract a slice
# `view_b` from `array_a` and broadcast the addition of 5 to view_b. Check if it alters the original `array_a

In [30]:
import numpy as np

array_a = np.arange(1, 13).reshape(4, 3)

view_b = array_a[1:3, 1:3]


view_b += 5


print("Original array array_a:")
print(array_a)


Original array array_a:
[[ 1  2  3]
 [ 4 10 11]
 [ 7 13 14]
 [10 11 12]]


In [31]:
# 79. Create a NumPy array `orig_array` of shape (2, 4) with values from 1 to 8. Create a reshaped view
# `reshaped_view` of shape (4, 2) from orig_array. Modify an element in `reshaped_view` and check if it
# reflects changes in the original `orig_array`.

In [32]:
import numpy as np

orig_array = np.arange(1, 9).reshape(2, 4)
reshaped_view = orig_array.reshape(4, 2)

print("Original array orig_array:")
print(orig_array)
print("\nReshaped view reshaped_view:")
print(reshaped_view)

reshaped_view[1, 1] = 999
print("\nAfter modifying reshaped_view:")
print("Original array orig_array:")
print(orig_array)
print("\nReshaped view reshaped_view:")
print(reshaped_view)


Original array orig_array:
[[1 2 3 4]
 [5 6 7 8]]

Reshaped view reshaped_view:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

After modifying reshaped_view:
Original array orig_array:
[[  1   2   3 999]
 [  5   6   7   8]]

Reshaped view reshaped_view:
[[  1   2]
 [  3 999]
 [  5   6]
 [  7   8]]


In [33]:
# 80. Create a NumPy array `data` of shape (3, 4) with random integers. Extract a copy `data_copy` of
# elements greater than 5. Modify an element in `data_copy` and verify if it affects the original `data`.

In [36]:
import numpy as np

# Create a NumPy array data of shape (3, 4) with random integers
data = np.random.randint(1, 10, size=(3, 4))

# Extract a copy data_copy of elements greater than 5
data_copy = data[data > 5].copy()

# Print the original array and the copy
print("Original array data:")
print(data)
print("\nCopied array data_copy:")
print(data_copy)

# Modify an element in data_copy
data_copy[0] = 999

# Check if it affects the original data
print("\nAfter modifying data_copy:")
print("Original array data:")
print(data)
print("\nModified copied array data_copy:")
print(data_copy)



Original array data:
[[5 3 8 6]
 [8 7 3 2]
 [4 2 1 8]]

Copied array data_copy:
[8 6 8 7 8]

After modifying data_copy:
Original array data:
[[5 3 8 6]
 [8 7 3 2]
 [4 2 1 8]]

Modified copied array data_copy:
[999   6   8   7   8]


In [37]:
# 81. Create two matrices A and B of identical shape containing integers and perform addition and subtraction
# operations between them.


In [38]:
import numpy as np

# Create matrix A
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# Create matrix B (with the same shape as A)
B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])

# Addition operation
addition_result = A + B

# Subtraction operation
subtraction_result = A - B

# Print the original matrices and the results of addition and subtraction
print("Matrix A:")
print(A)
print("\nMatrix B:")
print(B)
print("\nAddition result (A + B):")
print(addition_result)
print("\nSubtraction result (A - B):")
print(subtraction_result)


Matrix A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix B:
[[9 8 7]
 [6 5 4]
 [3 2 1]]

Addition result (A + B):
[[10 10 10]
 [10 10 10]
 [10 10 10]]

Subtraction result (A - B):
[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]


In [39]:
# 82. Generate two matrices `C` (3x2) and `D` (2x4) and perform matrix multiplication.

In [40]:
import numpy as np

# Generate matrix C (3x2)
C = np.array([[1, 2],
              [3, 4],
              [5, 6]])

# Generate matrix D (2x4)
D = np.array([[7, 8, 9, 10],
              [11, 12, 13, 14]])

# Perform matrix multiplication
multiplication_result = np.dot(C, D)

# Print the matrices and the result of matrix multiplication
print("Matrix C:")
print(C)
print("\nMatrix D:")
print(D)
print("\nResult of matrix multiplication (C * D):")
print(multiplication_result)


Matrix C:
[[1 2]
 [3 4]
 [5 6]]

Matrix D:
[[ 7  8  9 10]
 [11 12 13 14]]

Result of matrix multiplication (C * D):
[[ 29  32  35  38]
 [ 65  72  79  86]
 [101 112 123 134]]


In [41]:
# 83. Create a matrix `E` and find its transpose.

In [42]:
import numpy as np

# Create matrix E
E = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# Find the transpose of matrix E
E_transpose = np.transpose(E)

# Print the original matrix and its transpose
print("Matrix E:")
print(E)
print("\nTranspose of matrix E:")
print(E_transpose)


Matrix E:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Transpose of matrix E:
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [43]:
# 84. Generate a square matrix `F` and compute its determinant.

In [44]:
import numpy as np

# Generate a square matrix F
F = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# Compute the determinant of matrix F
determinant_F = np.linalg.det(F)

# Print the matrix F and its determinant
print("Matrix F:")
print(F)
print("\nDeterminant of matrix F:", determinant_F)


Matrix F:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Determinant of matrix F: 0.0


In [ ]:
# 85. Create a square matrix `G` and find its inverse.

In [45]:
import numpy as np

# Create a square matrix G
G = np.array([[1, 2],
              [3, 4]])

# Find the inverse of matrix G
inverse_G = np.linalg.inv(G)

# Print the original matrix and its inverse
print("Matrix G:")
print(G)
print("\nInverse of matrix G:")
print(inverse_G)


Matrix G:
[[1 2]
 [3 4]]

Inverse of matrix G:
[[-2.   1. ]
 [ 1.5 -0.5]]
